ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^user/',include('tt_user.urls')),
    url('^',include('tt_goods.urls')),
    url('^cart/',include('tt_cart.urls')),
    url('^order/',include('tt_order.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^search/', include('haystack.urls')),
]

ttsx/apps/tt_order/models.py
from django.db import models
from utils.models import BaseModel
from tt_user.models import User, Address
from tt_goods.models import GoodsSKU

class OrderInfo(BaseModel):
    """订单信息"""
    PAY_METHODS = {
        1: "货到付款",
        2: "支付宝",
    }

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "ALIPAY": 2
    }

    PAY_METHOD_CHOICES = (
        (1, "货到付款"),
        (2, "支付宝"),
    )

    ORDER_STATUS = {
        1: "待支付",
        2: "待发货",
        3: "待收货",
        4: "待评价",
        5: "已完成",
    }

    ORDER_STATUS_ENUM = {
        "UNPAID": 1,
        "UNSEND": 2,
        "UNRECEIVED": 3,
        "UNCOMMENT": 4,
        "FINISHED": 5
    }

    ORDER_STATUS_CHOICES = (
        (1, "待支付"),
        (2, "待发货"),
        (3, "待收货"),
        (4, "待评价"),
        (5, "已完成"),
    )

    order_id = models.CharField(max_length=64, primary_key=True, verbose_name="订单号")
    user = models.ForeignKey(User, verbose_name="下单用户")
    address = models.ForeignKey(Address, verbose_name="收获地址")
    total_count = models.IntegerField(default=1, verbose_name="商品总数")
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="商品总金额")
    trans_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="运费")
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=1, verbose_name="支付方式")
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name="订单状态")
    trade_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name="支付编号")

    class Meta:
        db_table = "df_order_info"


class OrderGoods(BaseModel):
    """订单商品"""
    order = models.ForeignKey(OrderInfo, verbose_name="订单")
    sku = models.ForeignKey(GoodsSKU, verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="单价")
    comment = models.TextField(default="", verbose_name="评价信息")

    class Meta:
        db_table = "df_order_goods"
# Create your models here.

ttsx/templates/base_bottom.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% block head %}{% endblock head %}
</head>

<body>

{% block body %}{% endblock body %}

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

ttsx/templates/base_goods.html
{% extends 'base_top.html' %}

{% block body1 %}

    <div class="search_bar clearfix">
        <a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_con fl"><form action="/search/" method="get">
            <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" value="搜索">
        </form></div>
        <div class="guest_cart fr">
            <a href="/cart/" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ total_count|default:0 }}</div>
        </div>
    </div>

    {% block body2 %}{% endblock body2 %}
{% endblock body1 %}

ttsx/templates/base_top.html
{% extends 'base_bottom.html' %}

{% block body %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if request.user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ request.user.username }}</em>
                        <span>|</span>
                        <a href="/user/logout">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/user/login">登录</a>
                        <span>|</span>
                        <a href="/user/register">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/user/info">用户中心</a>
                    <span>|</span>
                    <a href="/cart/">我的购物车</a>
                    <span>|</span>
                    <a href="user_center_order.html">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    {% block body1 %}{% endblock body1 %}

{% endblock body %}

ttsx/templates/base_user.html
{% extends 'base_top.html' %}

{% block body1 %}

    <div class="search_bar clearfix">
        <a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    {% block body2 %}{% endblock body2 %}
{% endblock body1 %}

ttsx/templates/detail.html
{% extends 'base_goods.html' %}

{% block body2 %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in category_list %}
                        <li><a href="/list{{ category.id }}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="/">首页</a></li>
                <li class="interval">|</li>
                <li><a href="/">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="/">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ sku.category.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.title }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unit }}</span>
            </div>
            <div class="total1">规格：
                {% for other in other_list %}
                    {% if other.id == sku.id %}
                        <em>{{ other.price }}/{{ other.unit }}</em>&nbsp;&nbsp;
                    {% else %}
                        <a href="/{{ other.id }}">{{ other.price }}/{{ other.unit }}</a>&nbsp;&nbsp;
                    {% endif %}
                {% endfor %}
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="hidden" id="sku_id" value="{{ sku.id }}">
                    <input type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>
            <div class="total">总价：<em>{{ sku.price }}元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new in new_list %}
                        <li>
                            <a href="/{{ new.id }}"><img src="{{ new.default_image.url }}"></a>
                            <h4><a href="/{{ new.id }}">{{ new.name }}</a></h4>
                            <div class="prize">￥{{ new.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">{{ sku.goods.desc|safe }}</div>

        </div>
    </div>

    <div class="add_jump"></div>

    <script type="text/javascript">
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;


        $('#add_cart').click(function () {
            $.post('/cart/add', {
                'sku_id': $('#sku_id').val(),
                'count': $('.num_show').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            }, function (data) {
                if (data.status == 1) {
                    $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'});
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7,
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                $('#show_count').html(data.total_count);
                            });
                        });
                }
            });
        });

        $('.num_show').blur(function () {
            //当数量失去焦点时，计算总价
            var num = parseInt($(this).val());
            var price = parseFloat($('.show_pirze>em').text());
            //验证num的有效性
            if (isNaN(num)) {//'abc'==>parseInt('abc')==>NaN not a number
                num = 1;
            }
            if (num < 1) {
                num = 1;
            }
            if (num > 5) {
                num = 5;
            }
            $(this).val(num);
            //计算总价
            var total = num * price;
            $('.total>em').text(total.toFixed(2) + '元');
        });
        //+1
        $('.add').click(function () {
            var num = parseInt($('.num_show').val());
            num++;
            $('.num_show').val(num).blur();//blur()模拟触发这个事件
        });
        //-1
        $('.minus').click(function () {
            var num = parseInt($('.num_show').val());
            num--;
            $('.num_show').val(num).blur();//blur()模拟触发这个事件
        });
    </script>
{% endblock body2 %}

ttsx/templates/fdfs_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{{ category.image.url }}">
</body>
</html>

ttsx/templates/index.html
{% extends 'base_goods.html' %}

{% block head %}
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock head %}

{% block body2 %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="/">首页</a></li>
                <li class="interval">|</li>
                <li><a href="/">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="/">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for category in category_list %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ category.logo }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for banner in banner_list %}
                    <li><a href="/{{ banner.sku.id }}"><img src="{{ banner.image.url }}"
                                                            alt="{{ banner.sku.name }}"></a></li>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for adv in adv_list %}
                <a href="{{ adv.url }}"><img src="{{ adv.image.url }}" alt="{{ adv.name }}"></a>
            {% endfor %}
        </div>
    </div>

    {% for category in category_list %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ category.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for title in category.title_list %}
                        <a href="/{{ title.sku.id }}">{{ title.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="/list{{ category.id }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ category.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for img in category.img_list %}
                        <li>
                            <h4><a href="/{{ img.sku.id }}">{{ img.sku.name }}</a></h4>
                            <a href="/{{ img.sku.id }}"><img src="{{ img.sku.default_image.url }}"></a>
                            <div class="prize">¥ {{ img.sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

    <script type="text/javascript" src="/static/js/slideshow.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock body2 %}

ttsx/templates/list.html
{% extends 'base_goods.html' %}

{% block body2 %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in category_list %}
					<li><a href="/list{{ category.id }}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="/">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="/">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ category_now.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new in new_list %}
					<li>
						<a href="/{{ new.id }}"><img src="{{ new.default_image.url }}"></a>
						<h4><a href="/{{ new.id }}">{{ new.name }}</a></h4>
						<div class="prize">￥{{ new.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="?order=1" {% if order == 1 %}class="active" {% endif %}>默认</a>
                {% if order == 2  %}
                <a href="?order=3" class="active">价格(升)</a>
                {% elif order == 3 %}
                <a href="?order=2" class="active">价格(降)</a>
                {% else %}
                 <a href="?order=2">价格</a>
                {% endif %}

				<a href="?order=4" {% if order == 4 %}class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in page %}
				<li>
					<a href="/{{ sku.id }}"><img src="{{ sku.default_image.url }}"></a>
					<h4><a href="/{{ sku.id }}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="javascript:;" id="{{ sku.id }}" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if page.has_previous %}
                    <a href="?pindex=1 &order={{ order }}">首页</a>
                    <a href="?pindex={{ page.number|add:-1 }}&order={{ order }}">上一页</a>
                {% else %}
                    <span>首页</span>
                    <span>上一页</span>
                {% endif %}

                {% for p in page_list %}
                    {% if p == page.number %}
                    <span class="active">{{ p }}</span>
                    {% else %}
                    <a href="?pindex={{ p }}&order={{ order }}">{{ p }}</a>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <a href="?pindex={{ page.number|add:1 }}&order={{ order }}">下一页</a>
                    <a href="?pindex={{ page.paginator.num_pages }}&order={{ order }}">末页</a>
                {% else %}
                    <span>下一页</span>
                    <span>末页</span>
                {% endif %}
			</div>
		</div>
	</div>

    <script>
    $('.add_goods').click(function () {
        $.post('/cart/add',{
            'sku_id':$(this).attr('id'),
            'count':1,
            'csrfmiddlewaretoken':'{{ csrf_token }}',
        },function (data) {
            if(data.status==1){
                alert('添加成功');
                $('#show_count').html(data.total_count);
            }

        });
    });


    </script>
{% endblock body2 %}

ttsx/templates/login.html
{% extends 'base_bottom.html' %}


{% block head %}{% endblock head %}

{% block body %}
    <div class="login_top clearfix">
        <a href="/index" class="login_logo"><img src="/static/images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="/user/register">立即注册</a>
                </div>
                <div class="form_input">
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ uname }}">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="{{ upwd }}">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="remember" value="1" checked="checked">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" value="登录" class="input_submit">
                        <div class="user_error1" style="display: block;">{{ err_msg }}</div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

ttsx/templates/place_order.html
{% extends 'base_user.html' %}
{% block head %}
    <script>
        $(function () {
            var total_count = 0, total_price = 0;
            $('.col07').each(function (i, n) {
                var price = parseFloat($(n).siblings('.col05').children('span').text());
                var count = parseInt($(n).prev().text());
                var total = price * count;
                $(n).children('em').text(total.toFixed(2));
                total_count += count;
                total_price += total;
            });
            $('.total_goods_count>em').text(total_count);
            $('.total_goods_count>b').text(total_price.toFixed(2) + '元');
            $('.total_pay>b').text((total_price + 10).toFixed(2) + '元');
        });
    </script>
{% endblock head %}
{% block body2 %}
    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            {% for addr in addr_list %}
                <dd><input type="radio" name="addr" value="{{ addr.id }}" {% if addr.isDefault %}checked="checked"{% endif %}>
                    {{ addr.province.title }} {{ addr.city.title }} {{ addr.district.title }} {{ addr.addr }}
                    （{{ addr.receiver }}收） {{ addr.phone_number }}
                </dd>
            {% endfor %}
        </dl>
        <a href="/user/site" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" value="1">
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style" value="2" checked="checked">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for sku in sku_list %}
            <ul class="goods_list_td clearfix">
                <li class="col01">
                    {{ forloop.counter }}
                    <input type="hidden" class="sku_id" value="{{ sku.id }}">
                </li>
                <li class="col02"><img src="{{ sku.default_image.url }}"></li>
                <li class="col03">{{ sku.name }}</li>
                <li class="col04">{{ sku.unit }}</li>
                <li class="col05"><span>{{ sku.price }}</span></li>
                <li class="col06">{{ sku.cart_count }}</li>
                <li class="col07"><em></em>元</li>
            </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em></em>件商品，总金额<b></b></div>
            <div class="transit">运费：<b>10元</b></div>
            <div class="total_pay">实付款：<b></b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn">提交订单</a>
    </div>

    <div class="popup_con">
        <div class="popup">
            <p>订单处理中，请稍等！</p>
        </div>

        <div class="mask"></div>
    </div>

    <script type="text/javascript">
        $('#order_btn').click(function () {
            $('.popup_con').fadeIn('fast');
            var s1 = '';
            $('.sku_id').each(function (i, n) {
                s1 += $(n).val() + ',';
            });
            $.post('/order/handle',{
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'addr_id': $('dl :checked').val(),
                'pay_style': $('.pay_style_con>:checked').val(),
                'sku_ids': s1,
            }, function (data) {
                $('.popup_con').fadeOut('fast');
                if (data.status == 1) {
                    location.href = '/user/order';
                } else if (data.status == 3) {//库存不足
                    location.href = '/cart/';
                }
            });
        });
    </script>

{% endblock body2 %}

ttsx/templates/user_center_order.html
{% extends 'base_user.html' %}
{% block head %}
    <script>
    $(function () {
        $('.col04').each(function (i,n) {
            var price=parseFloat($(n).prev().prev().find('span').text());
            var count=parseInt($(n).prev().text());
            var total=price*count;
            $(n).text(total.toFixed(2)+'元');
        });
    });
    </script>
{% endblock head %}

{% block body2 %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info">· 个人信息</a></li>
				<li><a href="#" class="active">· 全部订单</a></li>
				<li><a href="/user/site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for order in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.update_date|date:'Y-m-j H:i:s' }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col03 stress">
                        {% if order.status == 1 %}
                            待支付
                        {% elif order.status == 2 %}
                            待发货
                        {% elif order.status == 3 %}
                            待收货
                        {% elif order.status == 4 %}
                            待评价
                        {% elif order.status == 5 %}
                            已完成
                        {% endif %}
                    </li>
				</ul>

				<table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="70%">
                            {% for detail in order.ordergoods_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ detail.sku.default_image.url }}"></li>
                                    <li class="col02">{{ detail.sku.name }}<em><span>{{ detail.price }}</span>元/{{ detail.sku.unit }}</em>
                                    </li>
                                    <li class="col03">{{ detail.count }}</li>
                                    <li class="col04"></li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="10%">{{ order.total_amount }}元</td>
                        <td width="10%">
                            {% if order.status == 1 %}
                                待支付
                            {% elif order.status == 2 %}
                                待发货
                            {% elif order.status == 3 %}
                                待收货
                            {% elif order.status == 4 %}
                                待评价
                            {% elif order.status == 5 %}
                                已完成
                            {% endif %}
                        </td>
                        <td width="10%">
                            {% if order.status == 1 %}
                                <a href="#" class="oper_btn">去付款</a>
                            {% elif order.status == 2 %}
                                &nbsp;
                            {% elif order.status == 3 %}
                                <a href="#" class="oper_btn">收货</a>
                            {% elif order.status == 4 %}
                                <a href="#" class="oper_btn">去评价</a>
                            {% elif order.status == 5 %}
                                已完成
                            {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                {% if page.has_previous %}
                    <a href="?pindex=1">首页</a>
                    <a href="?pindex={{ page.number|add:-1 }}">上一页</a>
                {% else %}
                    <span>首页</span>
                    <span>上一页</span>
                {% endif %}


                {% for p in page_list %}
                    {% if p == page.number %}
                        <span class="active">{{ p }}</span>
                    {% else %}
                        <a href="?pindex={{ p }}">{{ p }}</a>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <a href="?pindex={{ page.number|add:1 }}">下一页</a>
                    <a href="?pindex={{ page.paginator.num_pages }}">末页</a>
                {% else %}
                    <span>下一页</span>
                    <span>末页</span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body2 %}